---
apiVersion: v1
kind: Pod
metadata:
  name: javawebappcpod
  labels:
    app: javawebapp #very important
spec:
  containers:
  - name: javawebappcontainer
    image: ashokit/javawebapp
    ports:
      - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: javawebappsvc
spec:
  type: NodePort
  selector:
    app: javawebapp # Label app name
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30501
...